### ISSUE TITLE
First letter (capitalized) is too high

### ISSUE THREAD

**Issue by gcfer** [pixelgrade/felt-free#10]
Possible enhancement. Probably the first letter of the first paragraph in posts is too high with respect to the baseline. Compared with other newspapers and also without comparing at all it seems that the letter is vertically shifted by some positive number of pixels. I don't know if it's due to the font or there is a box that is shifted. You may want to consider whether to shift it down a little bit. 
![image](https://user-images.githubusercontent.com/23129394/63854496-93e7c800-c99d-11e9-975c-b45798a5f012.png)

**Comment by madalingorbanescu** [comment]
Hello @gcfer

Good catch. The issue has been fixed in 9d15c745f1dfee99d9265bcc3361f3a4d37325b4
