### ISSUE TITLE
Lazy loading for images

### ISSUE THREAD

**Issue by scottmallinson** [pixelgrade/felt-free#12]
Add loading='lazy' to images to reduce loading times in browsers that support native lazy loading.

**the_post_thumbnail()** supports attributes as a second parameter. Pass ['loading' => 'lazy'] so that images are only loaded when in the viewport.

[Lazy Loading Images and Video](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/)

**Comment by scottmallinson** [comment]
Submitted pull request to fix this issue #15

**Comment by gcfer** [comment]
Does it work with any plugin or is developed internally in the package? If I just add a plugin, the end result is not so pleasing to the eye.

**Comment by scottmallinson** [comment]
@gcfer I've added it to the theme and it doesn't require any plugins. It's using the lazy loading HTML attribute that is, at the time of writing, only supported by Google Chrome 76+ and Android Browser 76+ (approx. 18% of global users).

https://caniuse.com/#feat=loading-lazy-attr

**Comment by gcfer** [comment]
Cool, thanks!

**Comment by georgeolaru** [comment]
@scottmallinson Native lazy loading for images is a nice step forward for this theme — thanks for the suggestion and for the pull request.

**Comment by madalingorbanescu** [comment]
Closed with 3850b642a6d3069dc6aeaf15a24a87dfdf9e0259 & 1b58c6202f56af496f8f82bdb459a76897f9c3ad
