### ISSUE TITLE
Fatal Error when calling felt_google_fonts_url() after install

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/felt-free#3]
Some users seem to get a fatal error after activating the Felt theme (version 2.4.2.1). Read more here.

Fatal error: Uncaught Error: Call to undefined function felt_google_fonts_url() in /srv/www/test-install/public_html/wp-content/themes/felt/functions.php:120

Thanks to @scottmallinson who proposed a temporary solution that we can use if we couldn't properly fix it:

Commenting out add_editor_style() on lines 118-123 and wp_enqueue_style() on line 167 in functions.php returns the WordPress install to a useable state allowing me to change to a different theme.

@vladolaru whenever you have some time, can you please take a look?

**Comment by vladolaru** [comment]
This issue was related to Windows environments, most likely development environments. The paths were to blame :(

**Comment by scottmallinson** [comment]
Hi @vladolaru,

Thanks for following up on this, but the fix hasn't resolved the issue.

On a clean Wordpress (5.2.2) install it's throwing the following error when activating the Felt 2.4.2.3 theme:

`Fatal error: Uncaught Error: Call to undefined function felt_google_fonts_url() in /srv/www/test/public_html/wp-content/themes/felt/functions.php:120 Stack trace: #0 /srv/www/test/public_html/wp-includes/class-wp-hook.php(286): felt_setup('') #1 /srv/www/test/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /srv/www/test/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /srv/www/test/public_html/wp-settings.php(509): do_action('after_setup_the...') #4 /srv/www/test/public_html/wp-config.php(80): require_once('/srv/www/test...') #5 /srv/www/test/public_html/wp-load.php(37): require_once('/srv/www/test...') #6 /srv/www/test/public_html/wp-admin/admin.php(34): require_once('/srv/www/test...') #7 /srv/www/test/public_html/wp-admin/index.php(10): require_once('/srv/www/test...') #8 {main} thrown in /srv/www/test/public_html/wp-content/themes/felt/functions.php on line 120

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.`

**Comment by vladolaru** [comment]
Hi @scottmallinson,

This is really weird. Could you try it with the following version and, with WP_DEBUG set to true, could you pass on the error or message given?

[felt.zip](https://github.com/pixelgrade/felt-free/files/3434549/felt.zip)

**Comment by scottmallinson** [comment]
Hi @vladolaru,

I've tried the ZIP you provided with WP_DEBUG set to true. The error message is the same as before:

`[26-Jul-2019 17:24:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function felt_google_fonts_url() in /srv/www/landsremote/public_html/wp-content/themes/felt/functions.php:120
Stack trace:
#0 /srv/www/landsremote/public_html/wp-includes/class-wp-hook.php(286): felt_setup('')
#1 /srv/www/landsremote/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /srv/www/landsremote/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /srv/www/landsremote/public_html/wp-settings.php(509): do_action('after_setup_the...')
#4 /srv/www/landsremote/public_html/wp-config.php(81): require_once('/srv/www/landsr...')
#5 /srv/www/landsremote/public_html/wp-load.php(37): require_once('/srv/www/landsr...')
#6 /srv/www/landsremote/public_html/wp-blog-header.php(13): require_once('/srv/www/landsr...')
#7 /srv/www/landsremote/public_html/index.php(17): require('/srv/www/landsr...')
#8 {main}
  thrown in /srv/www/landsremote/public_html/wp-content/themes/felt/functions.php on line 120
[26-Jul-2019 17:25:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function felt_google_fonts_url() in /srv/www/landsremote/public_html/wp-content/themes/felt/functions.php:120
Stack trace:
#0 /srv/www/landsremote/public_html/wp-includes/class-wp-hook.php(286): felt_setup('')
#1 /srv/www/landsremote/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /srv/www/landsremote/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /srv/www/landsremote/public_html/wp-settings.php(509): do_action('after_setup_the...')
#4 /srv/www/landsremote/public_html/wp-config.php(81): require_once('/srv/www/landsr...')
#5 /srv/www/landsremote/public_html/wp-load.php(37): require_once('/srv/www/landsr...')
#6 /srv/www/landsremote/public_html/wp-blog-header.php(13): require_once('/srv/www/landsr...')
#7 /srv/www/landsremote/public_html/index.php(17): require('/srv/www/landsr...')
#8 {main}
  thrown in /srv/www/landsremote/public_html/wp-content/themes/felt/functions.php on line 120
` 

This time I have tried it in a different Wordpress install where a different (Wordpress default) theme is working fine.
