### ISSUE TITLE
Issue when resizing browser window from Mobile to Desktop

### ISSUE THREAD

**Issue by gcfer** [pixelgrade/felt-free#7]
There is an issue when resizing the browser window (making it first smaller and then larger again).

**Comment by gcfer** [comment]
Another related issue is that, if you open the website with an iPhone, you don't see the first picture at all (do it yourself with an iPhone, or check it [here](http://quirktools.com/screenfly/#u=https%3A//demos.pixelgrade.com/felt-lite/&w=375&h=667&a=37&s=1)).

**Comment by georgeolaru** [comment]
Thanks for noticing GC! 
​
​There are some JavaScript functions that are called to switch the Slider layout when downsizing and I don't think they are called again when resizing the window back to a larger screen.

Even if there might be limited cases when this could happen (from desktop to mobile and to desktop again), we will look into it for a solution.

**Comment by georgeolaru** [comment]
@gcfer I just tested again the resizing issue and it seems that the Slider take back its shape both ways (from Mobile to Desktop and from Desktop to Mobile): https://cl.ly/ce1e1e

Can you please have a look and let me know if you still have this issue?

**Comment by gcfer** [comment]
Great job! It works fine now. I just want to point out though that the behavior is different from the pro version—I don't think it's worse, just different—because there is no picture when reducing the size.

**Comment by madalingorbanescu** [comment]
I am going to close this issue because it's invalid.
