### ISSUE TITLE
Issue with Slider image on Mobile

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/felt-free#9]
@gcfer mentioned this in #7:
>  if you open the website with an iPhone, you don't see the first picture at all (do it yourself with an iPhone, or check it here): http://quirktools.com/screenfly/#u=https%3A//demos.pixelgrade.com/felt-lite/&w=375&h=667&a=37&s=1

It seems that in the PRO version there isn't this problem and we can find a way to apply the fix here too.

**Comment by gcfer** [comment]
> It seems that in the PRO version there isn't this problem and we can find a way to apply the fix here too.

That would be cool!
